 //Operadores de operacion: Que son operadores que nos van a ayudar a hacer operaciones matematicas.

 //Estos son operadores que nos ayudan a hacer operaciones matematicas, pero tambien son conocidos como operadores binarios. Porque es un operador generando algo entre dos valores, dos variables. Por estas dos variables se conocen como operadores binarios.
 //De igual forma no solo podemos ocupar estos operadores con numeros.

 3 + 2 // 5
 50 - 10 //40
 10 * 20 //200
 20 / 2 //10





//Concatenacion
"Juan " + "Gutierrez"  //"Juan Gutiérrez"
//El signo + genera una concatenación, lo unico que hace es tomar los dos valores y simplemente los junta en uno y nos regresa un solo valor que en string, podemos ocupar tambien este operador de + para poder hacer esta concatenacion




! //Caracter de admiracion. Donde significa que es un no, es una negacion.

!false  //true



//Operadores de asignacion
var a = 1;  //con este valor de = Le estamos asignando el valor a la variable que ya declaramos, la estamos inicializando, asignandole un valor.
//Este un igual, simplemente nos ayuda asignar valores, pero tenemos operadores que son dos iguales y tres iguales que nos van a ayudar a comparar.

3 == "3"; // True, porque este valor de dos iguales esta comparando, lo que va a comparar es no tanto el tipo de valor, sino el valor 3.
//Solo esta comparando el valor 3 y 3 es lo mismo.

3 === "3";  // False, porque este esta simplemente validando que los dos tipos y valores sean estrictamente iguales. Entonces dice que hay un valor que es 3, tambien hay un valor que es tres, pero un valor es tipo numero y el otro valor es tipo string. Entonces esto claramente ya no es verdad. Nos genera falso



//Tenemos otros valores de comparacion









